export const Professions = [
  'Academic Researcher',
  'Acupuncturist',
  'Athletic Trainer',
  'Business Coach',
  'Chiropractor',
  'Clinical / Hospital Researcher',
  'Counsellor',
  'Dentist / Dental Surgeon',
  'Float Center Owner / Operator',
  'Health Educator',
  'Hospital System Administrator',
  'Human Resources Coordinator',
  'Hypnotherapist',
  'Independent / Private Researcher',
  'Life Coach', 'Massage Therapist',
  'Meditation / Mindfulness Instructor',
  'Midwife', 'Naturopathic Doctor',
  'Neurofeedback Practitioner',
  'Nurse', 'Nutritionist / Dietitian',
  'Occupational Therapist',
  'Osteopath',
  'Paramedic',
  'Pharmacist',
  'Physical Therapist',
  'Physician',
  'Psychiatrist',
  'Psychologist',
  'Psychotherapist',
  'Public Health Worker',
  'Social Worker',
  'Sports Coach',
  'Veterinarian',
  'Other'
]

export const qualifyingProfessions = [
  'Academic Researcher',
  'Acupuncturist',
  'Athletic Trainer',
  'Business Coach',
  'Chiropractor',
  'Clinical / Hospital Researcher',
  'Counsellor',
  'Dentist / Dental Surgeon',
  'Float Center Owner / Operator',
  'Health Educator',
  'Hospital System Administrator',
  'Human Resources Coordinator',
  'Hypnotherapist',
  'Independent / Private Researcher',
  'Life Coach', 'Massage Therapist',
  'Meditation / Mindfulness Instructor',
  'Midwife', 'Naturopathic Doctor',
  'Neurofeedback Practitioner',
  'Nurse', 'Nutritionist / Dietitian',
  'Occupational Therapist',
  'Osteopath',
  'Paramedic',
  'Pharmacist',
  'Physical Therapist',
  'Physician',
  'Psychiatrist',
  'Psychologist',
  'Psychotherapist',
  'Public Health Worker',
  'Social Worker',
  'Sports Coach',
  'Veterinarian'
]

export const qualifyingDegrees = {
  DMin: 'Doctor of Ministry',
  DO: 'Doctor of Osteopathy',
  DrPH: 'Doctor of Public Health',
  DSW: 'Doctor of Social Work',
  EdD: 'Doctor of Education',
  EdM: 'Master of Education',
  MA: 'Master of Arts',
  MAH: 'Master of Arts in Human Services',
  MC: 'Master of Counseling',
  MD: 'Doctor of Medicine',
  MDiv: 'Masters in Divinity',
  Med: 'Master of Education',
  MPH: 'Master of Public Health',
  MPS: 'Master of Professional Studies',
  MS: 'Master of Science',
  MSc: 'Master of Science',
  MSEd: 'Master of Science in Education',
  MSN: 'Master of Science in Nursing',
  MSS: 'Master of Social Science',
  MSSW: 'Master of Science in Social Work',
  MSW: 'Master of Social Work',
  PhD: 'Doctor of Philosophy',
  PsyaD: 'Doctor of Psychoanalysis'
}

export const licensesAndCertifications = {
  ABECSW: 'American Board of Examiners in Clinical Social Work',
  ABFamP: 'American Board of Family Psychology',
  ABPN: 'American Board of Professional Neuropsychology',
  ABPP: 'American Board of Professional Psychology',
  ACSW: 'Academy of Clinical Social Workers',
  ADTR: 'Academy of Dance Therapists Registered',
  APRN: 'Advanced Practice Registered Nurse',
  ATR: 'Registered Art Therapist',
  'ATR-BC': 'Registered Art Therapist - Board Certified',
  BCBT: 'Board Certification in Bereavement Trauma™',
  BCD: 'Board Certified Diplomate in Clinical Social Work',
  BCDT: 'Board Certification in Disability Trauma™',
  BCDV: 'Board Certification in Domestic Violence™',
  BCETS: 'Board Certified Expert in Traumatic Stress™',
  BCFT: 'Board Certification in Forensic Traumatology™',
  BCIT: 'Board Certification in Illness Trauma™',
  BCMVT: 'Board Certification in Motor Vehicle Trauma™',
  BCPM: 'Board Certification in Pain Management™',
  BCRT: 'Board Certification in Rape Trauma™',
  BCSA: 'Board Certification in Sexual Abuse™',
  BCSCR: 'Board Certification in School Crisis Response™',
  BCSM: 'Board Certification in Stress Management™',
  BCUCR: 'Board Certification in University Crisis Response™',
  CAC: 'Certified Addictions Counselor -or- Certified Alcoholism Counselor',
  CADAC: 'Certified Alcohol and Drug Abuse Counselor',
  CADC: 'Certified Alcohol and Drug Counselor',
  CAMF: 'Certified Anger Management Facilitator',
  CAP: 'Certified Addictions Professional',
  CART: 'Certified Anger Resolution Therapist',
  CAS: 'Certified Addiction Specialist',
  CASAC: 'Certified Alcohol and Substance Abuse Counselor',
  CBT: 'Certified Bioenergetic Therapist',
  CCADC: 'Certified Clinical Alcohol and Drug Counselor',
  CCDP: 'Certified Chemical Dependency Professional',
  CCHT: 'Certified Clinical Hypnotherapist',
  CCPT: 'Certified Clinical Pastoral Therapist',
  CCMH: 'Clinical Counselor in Mental Health',
  CCMHC: 'Certified Clinical Mental Health Counselor',
  CCSW: 'Certified Clinical Social Worker',
  CEAP: 'Certified Employee Assistance Professional',
  CEDS: 'Certified Eating Disorders Specialist',
  CFLE: 'Certified Family Life Educator',
  CGP: 'Certified Group Psychotherapist',
  CHT: 'Certified Hypnotherapist',
  CICSW: 'Certified Independent Clinical Social Worker',
  CISW: 'Certified Independent Social Worker',
  CMFT: 'Certified Marriage and Family Therapist',
  CP: 'Certified Psychologist -or- Clinical Psychologist',
  CpastC: 'Certified Pastoral Counselor',
  CPC: 'Certified Professional Counselor',
  CRADC: 'Certified Reciprocal Alcohol and Drug Counselor',
  CRC: 'Certified Rehabilitation Counselor',
  CSAC: 'Certified Substance Abuse Counselor',
  CSW: 'Certified Social Worker -or- Clinical Social Worker',
  'CSW-C': 'Certified Social Worker - Clinical',
  DAPA: 'Diplomate, American Psychotherapy Association',
  DCSW: 'Diplomate in Clinical Social Work',
  'DOT SAP': 'Department of Transportation Substance Abuse Professional',
  DTR: 'Dance Therapist Registered',
  'iPEC, ACC': 'International Coach Federation',
  LAC: 'Licensed Associate Counselor',
  LADAC: 'Licensed Alcohol and Drug Abuse Counselor',
  LADC: 'Licensed Alcohol and Drug Counselor',
  LAMFT: 'Licensed Associate Marriage and Family Therapist',
  LAPC: 'Licensed Associate Professional Counselor',
  LASAC: 'Licensed Associate Substance Abuse Counselor',
  LCADC: 'Licensed Clinical Alcohol and Drug Counselor',
  LCAS: 'Licensed Clinical Addictions Specialist',
  LCAT: 'Licensed Creative Arts Therapist',
  LCDC: 'Licensed Chemical Dependency Counselor',
  LCDP: 'Licensed Chemical Dependency Professional',
  LCMFT: 'Licensed Clinical Marriage and Family Therapist',
  LCMHC: 'Licensed Clinical Mental Health Counselor',
  LCP: 'Licensed Clinical Psychologist -or- Licensed Counseling Professional',
  LCPC: 'Licensed Clinical Professional Counselor',
  LCSW: 'Licensed Clinical Social Worker',
  'LCSW-C': 'Licensed Certified Social Worker-Clinical',
  LGSW: 'Licensed Graduate Social Worker',
  LICSW: 'Licensed Independent Clinical Social Worker',
  LIMFT: 'Licensed Independent Marriage and Family Therapist',
  LISW: 'Licensed Independent Social Worker',
  'LISW-CP': 'Licensed Independent Social Worker - Clinical Practice',
  LLP: 'Limited Licensed Psychologist',
  LMFT: 'Licensed Marriage and Family Therapist',
  LMHC: 'Licensed Mental Health Counselor',
  LMHP: 'Licensed Mental Health Practitioner',
  LMSW: 'Licensed Master Social Worker',
  'LMSW-ACP': 'Licensed Master Social Worker - Advanced Clinical Practitioner',
  LP: 'Licensed Psychoanalyst -or- Licensed Psychologist',
  LPA: 'Licensed Psychological Associate',
  LpastC: 'Licensed Pastoral Counselor',
  LPC: 'Licensed Professional Counselor',
  LPCC: 'Licensed Professional Clinical Counselor',
  LPCMH: 'Licensed Professional Counselor of Mental Health',
  LPE: 'Licensed Psychological Examiner',
  LPP: 'Licensed Pastoral Psychotherapist',
  LSATP: 'Licensed Substance Abuse Treatment Practitioner',
  LSCSW: 'Licensed Specialist Clinical Social Worker',
  LSP: 'Licensed School Psychologist',
  LSW: 'Licensed Social Worker',
  MAC: 'Master Addiction Counselor - also offered by NAADAC',
  MFCC: 'Marriage, Family and Child Counselor',
  MFT: 'Marriage and Family Therapist',
  'MT-BC': 'Music Therapist - Board Certified',
  NBCCH: 'National Board Certified Clinical Hypnotherapist',
  NBCDCH: 'National Board Certified Diplomate in Clinical Hypnotherapy',
  NCC: 'National Certified Counselor',
  NCPsyA: 'Nationally Certified Psychoanalyst',
  NCSC: 'National Certified School Counselor',
  PA: 'Psychological Associate',
  PLMHP: 'Provisionally Licensed Mental Health Practitioner',
  PLPC: 'Provisional Licensed Professional Counselor',
  PMHNP: 'Psychiatric Mental Health Nurse Practitioner',
  RAS: 'Registered Addiction Specialist',
  RDT: 'Registered Drama Therapist',
  REAT: 'Registered Expressive Arts Therapist',
  RN: 'Registered Nurse',
  RPC: 'Registered Professional Counselor',
  RPT: 'Registered Play Therapist',
  'RPT-S': 'Registered Play Therapist-Supervisor',
  SAP: 'Substance Abuse Professional',
  SW: 'Social Worker',
  TLLP: 'Temporary Limited License Psychologist'
}

export default {
  Professions,
  qualifyingProfessions,
  qualifyingDegrees,
  licensesAndCertifications
}
